[package]
name = "ayaml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ayaml"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"
pythonize = "0.23.0"
serde = "1.0"
yaml-rust2 = "0.9.0"
